### ISSUE TITLE
neighbours does not produce expected result.

### ISSUE THREAD

**Issue by osunderdog** [tjguk/dojo-board#8]
The readme shows the results from executing neighbours:

```
b1 = board.Board((3, 3, 3))
list(b1.neighbours((0, 0, 0)))
# [(0, 1, 1), (1, 1, 0), ..., (1, 0, 1), (0, 1, 0)]
```
the ellipsis doesn't show all values, but I can see that there are at least 4 items listed. However when I run this:
```
b1 = board.Board((3, 3, 3))
neighbours = list(b1.neighbours((0, 0, 0)))
neighbours
[(0, 0, 1), (0, 1, 0), (1, 0, 0)]
```
The result shows 3 values rather than 4 or more.  

I see there are no tests for neighbours in the test suite.

**Comment by tjguk** [comment]
Well thanks for taking the trouble to report this, @osunderdog  -- I've added a fix (and some tests!)
